/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as PublicMusicRouteImport } from './routes/_public.music'
import { Route as PublicAboutRouteImport } from './routes/_public.about'
import { Route as PublicProjectsIndexRouteImport } from './routes/_public.projects.index'
import { Route as PublicBlogIndexRouteImport } from './routes/_public.blog.index'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicMusicRoute = PublicMusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const PublicProjectsIndexRoute = PublicProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBlogIndexRoute = PublicBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => PublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/about': typeof PublicAboutRoute
  '/music': typeof PublicMusicRoute
  '/blog/': typeof PublicBlogIndexRoute
  '/projects/': typeof PublicProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof PublicAboutRoute
  '/music': typeof PublicMusicRoute
  '/': typeof PublicIndexRoute
  '/blog': typeof PublicBlogIndexRoute
  '/projects': typeof PublicProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/_public/about': typeof PublicAboutRoute
  '/_public/music': typeof PublicMusicRoute
  '/_public/': typeof PublicIndexRoute
  '/_public/blog/': typeof PublicBlogIndexRoute
  '/_public/projects/': typeof PublicProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/music' | '/blog/' | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/music' | '/' | '/blog' | '/projects'
  id:
    | '__root__'
    | '/_public'
    | '/_public/about'
    | '/_public/music'
    | '/_public/'
    | '/_public/blog/'
    | '/_public/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/music': {
      id: '/_public/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof PublicMusicRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/projects/': {
      id: '/_public/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof PublicProjectsIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/blog/': {
      id: '/_public/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof PublicBlogIndexRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicMusicRoute: typeof PublicMusicRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicBlogIndexRoute: typeof PublicBlogIndexRoute
  PublicProjectsIndexRoute: typeof PublicProjectsIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicMusicRoute: PublicMusicRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicBlogIndexRoute: PublicBlogIndexRoute,
  PublicProjectsIndexRoute: PublicProjectsIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
